version: '3.8'

services:
  backend:
    build: .
    container_name: share-sampatti-backend
    ports:
      - "7000:7000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

